/*
 * This file is generated by jOOQ.
*/
package com.swnote.jooq.generator;


import com.swnote.jooq.generator.tables.FlywaySchemaHistory;
import com.swnote.jooq.generator.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.swnote.jooq.generator.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * 用户信息
     */
    public static final User USER = com.swnote.jooq.generator.tables.User.USER;
}
